<a href="https://colab.research.google.com/github/Tejanjanidevi/FML/blob/main/Copy_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

zero dimensional array

In [ ]:
a=np.array(12)
print(a)

12


one dimensional array

In [ ]:
a=np.array([120,80,50])
print(a)

[120  80  50]


In [ ]:
a=np.arange(12,80,5)
print(a)

[12 17 22 27 32 37 42 47 52 57 62 67 72 77]


In [ ]:
a=np.array([120,80,50])
b=np.array((120,80,50))
print(a)
print(b)

[120  80  50]
[120  80  50]


Two dimensional array

In [ ]:
a=np.array([[120,80,50],[120,80,50]])
print(a)

[[120  80  50]
 [120  80  50]]


In [ ]:
a=np.array(((120,80,50),(120,80,50)))
print(a)

[[120  80  50]
 [120  80  50]]


Three dimensional array

In [ ]:
a=np.array([[[120,80,50],[120,80,50]],[[120,80,50],[120,80,50]]])
print(a)

[[[120  80  50]
  [120  80  50]]

 [[120  80  50]
  [120  80  50]]]


In [4]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
a=np.zeros([5,5,5])
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [8]:
a=np.full([4,4],4)
print(a)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [9]:
a=np.random.rand(4,4)
print(a)

[[0.52975696 0.69138969 0.36754846 0.03816138]
 [0.33074655 0.43387518 0.1850119  0.63043202]
 [0.87052069 0.62117834 0.22026578 0.45920715]
 [0.80473921 0.71132177 0.44939463 0.04531757]]


In [11]:
a=np.ones([5,5,5])
print(a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [12]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
a=np.arange(5,95,5)
print(a)

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90]


In [20]:
a=np.linspace(5,95,5)
print(a)

[ 5.  27.5 50.  72.5 95. ]


In [21]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]
